import { StyleSheet } from 'react-native';
import { theme } from '../theme';

export const styles = StyleSheet.create({
    root: { flex: 1, backgroundColor: theme.bg },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: theme.border,
    },
    headerRight: { alignItems: 'flex-end', maxWidth: '45%' },
    nodeName: { color: theme.text, fontSize: 20, fontWeight: '700' },
    nodeId: { color: theme.faint, fontSize: 12, fontFamily: theme.mono, marginTop: 2 },
    radioRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    dot: { width: 8, height: 8, borderRadius: 4 },
    radioText: { color: theme.dim, fontSize: 13 },
    radioDetail: { color: theme.faint, fontSize: 11, marginTop: 2 },

    tabs: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: theme.border },
    tab: { flex: 1, paddingVertical: 10, alignItems: 'center' },
    tabOn: { borderBottomWidth: 2, borderBottomColor: theme.accent },
    tabText: { color: theme.faint, fontSize: 12, letterSpacing: 1 },
    tabTextOn: { color: theme.text },

    searchBar: { flexDirection: 'row', padding: 12, gap: 8 },
    input: {
        flex: 1,
        backgroundColor: theme.panel,
        borderWidth: 1,
        borderColor: theme.border,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        color: theme.text,
        fontSize: 15,
    },
    button: {
        backgroundColor: theme.accent,
        borderRadius: 8,
        paddingHorizontal: 18,
        paddingVertical: 12,
        justifyContent: 'center',
        minWidth: 64,
        alignItems: 'center',
    },
    buttonBusy: { backgroundColor: theme.accentDim },
    buttonText: { color: theme.bg, fontWeight: '700', letterSpacing: 1 },
    summary: { color: theme.dim, fontSize: 12, paddingHorizontal: 16, paddingBottom: 6 },

    listPad: { padding: 12, gap: 10, paddingBottom: 40 },
    empty: { color: theme.faint, fontSize: 14, textAlign: 'center', padding: 24, lineHeight: 20 },

    hit: {
        backgroundColor: theme.panel,
        borderWidth: 1,
        borderColor: theme.border,
        borderRadius: 10,
        padding: 12,
    },
    hitTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
    hitTitle: { color: theme.text, fontSize: 15, fontWeight: '600', flex: 1 },
    hitScore: { color: theme.accent, fontSize: 12, fontFamily: theme.mono },
    hitBadge: { color: theme.faint, fontSize: 11, marginTop: 4, fontFamily: theme.mono },
    hitText: { color: theme.dim, fontSize: 13, marginTop: 8, lineHeight: 19 },

    sectionTitle: {
        color: theme.faint,
        fontSize: 11,
        letterSpacing: 1.5,
        marginTop: 12,
        marginBottom: 2,
    },
    card: {
        backgroundColor: theme.panel,
        borderWidth: 1,
        borderColor: theme.border,
        borderRadius: 10,
        padding: 12,
    },
    cardWarn: { borderColor: theme.warn },
    cardTitle: { color: theme.text, fontWeight: '600', fontSize: 14, marginBottom: 4 },
    cardBody: { color: theme.dim, fontSize: 13, lineHeight: 19 },

    statRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 3 },
    statLabel: { color: theme.dim, fontSize: 13 },
    statValue: { color: theme.text, fontSize: 13, fontFamily: theme.mono },

    coverageRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
    chip: {
        borderWidth: 1,
        borderColor: theme.border,
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 6,
    },
    chipOn: { borderColor: theme.accent, backgroundColor: theme.accentDim },
    chipText: { color: theme.dim, fontSize: 12 },
    chipTextOn: { color: theme.text },

    logRow: { flexDirection: 'row', gap: 8, alignItems: 'flex-start' },
    logKind: { fontSize: 10, fontFamily: theme.mono, width: 58, textTransform: 'uppercase' },
    logLabel: { color: theme.dim, fontSize: 12, fontFamily: theme.mono, flex: 1 },
});
